server:
  servlet:
    context-path: "/hercules"

spring:
  application:
    name: hercules

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/master-changelog.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_URL}

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
  use-management-port: true

management:
  server:
    port: 9080  # Management port
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
